#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcibademProje.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AcibademProje")]
	public partial class AcibademDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAltGrup(tblAltGrup instance);
    partial void UpdatetblAltGrup(tblAltGrup instance);
    partial void DeletetblAltGrup(tblAltGrup instance);
    partial void InserttblTakipVerileri(tblTakipVerileri instance);
    partial void UpdatetblTakipVerileri(tblTakipVerileri instance);
    partial void DeletetblTakipVerileri(tblTakipVerileri instance);
    partial void InserttblDemografik(tblDemografik instance);
    partial void UpdatetblDemografik(tblDemografik instance);
    partial void DeletetblDemografik(tblDemografik instance);
    partial void InserttblDrListesi(tblDrListesi instance);
    partial void UpdatetblDrListesi(tblDrListesi instance);
    partial void DeletetblDrListesi(tblDrListesi instance);
    partial void InserttblHastaBilgileri(tblHastaBilgileri instance);
    partial void UpdatetblHastaBilgileri(tblHastaBilgileri instance);
    partial void DeletetblHastaBilgileri(tblHastaBilgileri instance);
    partial void InserttblKOMorbidite(tblKOMorbidite instance);
    partial void UpdatetblKOMorbidite(tblKOMorbidite instance);
    partial void DeletetblKOMorbidite(tblKOMorbidite instance);
    partial void InserttblOperasyonTuru(tblOperasyonTuru instance);
    partial void UpdatetblOperasyonTuru(tblOperasyonTuru instance);
    partial void DeletetblOperasyonTuru(tblOperasyonTuru instance);
    partial void InserttblOperatifOzellikler(tblOperatifOzellikler instance);
    partial void UpdatetblOperatifOzellikler(tblOperatifOzellikler instance);
    partial void DeletetblOperatifOzellikler(tblOperatifOzellikler instance);
    partial void InserttblPatoloji(tblPatoloji instance);
    partial void UpdatetblPatoloji(tblPatoloji instance);
    partial void DeletetblPatoloji(tblPatoloji instance);
    partial void InserttblPatolojikVeriler(tblPatolojikVeriler instance);
    partial void UpdatetblPatolojikVeriler(tblPatolojikVeriler instance);
    partial void DeletetblPatolojikVeriler(tblPatolojikVeriler instance);
    partial void InserttblPosOperatifOzellikleri(tblPosOperatifOzellikleri instance);
    partial void UpdatetblPosOperatifOzellikleri(tblPosOperatifOzellikleri instance);
    partial void DeletetblPosOperatifOzellikleri(tblPosOperatifOzellikleri instance);
    #endregion
		
		public AcibademDataContext() : 
				base(global::AcibademProje.Properties.Settings.Default.AcibademProjeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AcibademDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AcibademDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AcibademDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AcibademDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAltGrup> tblAltGrups
		{
			get
			{
				return this.GetTable<tblAltGrup>();
			}
		}
		
		public System.Data.Linq.Table<tblTakipVerileri> tblTakipVerileris
		{
			get
			{
				return this.GetTable<tblTakipVerileri>();
			}
		}
		
		public System.Data.Linq.Table<tblDemografik> tblDemografiks
		{
			get
			{
				return this.GetTable<tblDemografik>();
			}
		}
		
		public System.Data.Linq.Table<tblDrListesi> tblDrListesis
		{
			get
			{
				return this.GetTable<tblDrListesi>();
			}
		}
		
		public System.Data.Linq.Table<tblHastaBilgileri> tblHastaBilgileris
		{
			get
			{
				return this.GetTable<tblHastaBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<tblKOMorbidite> tblKOMorbidites
		{
			get
			{
				return this.GetTable<tblKOMorbidite>();
			}
		}
		
		public System.Data.Linq.Table<tblOperasyonTuru> tblOperasyonTurus
		{
			get
			{
				return this.GetTable<tblOperasyonTuru>();
			}
		}
		
		public System.Data.Linq.Table<tblOperatifOzellikler> tblOperatifOzelliklers
		{
			get
			{
				return this.GetTable<tblOperatifOzellikler>();
			}
		}
		
		public System.Data.Linq.Table<tblPatoloji> tblPatolojis
		{
			get
			{
				return this.GetTable<tblPatoloji>();
			}
		}
		
		public System.Data.Linq.Table<tblPatolojikVeriler> tblPatolojikVerilers
		{
			get
			{
				return this.GetTable<tblPatolojikVeriler>();
			}
		}
		
		public System.Data.Linq.Table<tblPosOperatifOzellikleri> tblPosOperatifOzellikleris
		{
			get
			{
				return this.GetTable<tblPosOperatifOzellikleri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAltGrup")]
	public partial class tblAltGrup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _AltGrup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAltGrupChanging(string value);
    partial void OnAltGrupChanged();
    #endregion
		
		public tblAltGrup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGrup", DbType="NVarChar(255)")]
		public string AltGrup
		{
			get
			{
				return this._AltGrup;
			}
			set
			{
				if ((this._AltGrup != value))
				{
					this.OnAltGrupChanging(value);
					this.SendPropertyChanging();
					this._AltGrup = value;
					this.SendPropertyChanged("AltGrup");
					this.OnAltGrupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTakipVerileri")]
	public partial class tblTakipVerileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _Postop3AyLokalNuks;
		
		private System.Nullable<decimal> _Postop3AyKreatin;
		
		private string _Postop6AyLokalNuks;
		
		private System.Nullable<decimal> _Postop6AyKreatin;
		
		private string _Postop12AyLokalNuks;
		
		private System.Nullable<decimal> _Postop12AyKreatin;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPostop3AyLokalNuksChanging(string value);
    partial void OnPostop3AyLokalNuksChanged();
    partial void OnPostop3AyKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostop3AyKreatinChanged();
    partial void OnPostop6AyLokalNuksChanging(string value);
    partial void OnPostop6AyLokalNuksChanged();
    partial void OnPostop6AyKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostop6AyKreatinChanged();
    partial void OnPostop12AyLokalNuksChanging(string value);
    partial void OnPostop12AyLokalNuksChanged();
    partial void OnPostop12AyKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostop12AyKreatinChanged();
    #endregion
		
		public tblTakipVerileri()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop3AyLokalNuks", DbType="NVarChar(5)")]
		public string Postop3AyLokalNuks
		{
			get
			{
				return this._Postop3AyLokalNuks;
			}
			set
			{
				if ((this._Postop3AyLokalNuks != value))
				{
					this.OnPostop3AyLokalNuksChanging(value);
					this.SendPropertyChanging();
					this._Postop3AyLokalNuks = value;
					this.SendPropertyChanged("Postop3AyLokalNuks");
					this.OnPostop3AyLokalNuksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop3AyKreatin", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> Postop3AyKreatin
		{
			get
			{
				return this._Postop3AyKreatin;
			}
			set
			{
				if ((this._Postop3AyKreatin != value))
				{
					this.OnPostop3AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._Postop3AyKreatin = value;
					this.SendPropertyChanged("Postop3AyKreatin");
					this.OnPostop3AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop6AyLokalNuks", DbType="NVarChar(5)")]
		public string Postop6AyLokalNuks
		{
			get
			{
				return this._Postop6AyLokalNuks;
			}
			set
			{
				if ((this._Postop6AyLokalNuks != value))
				{
					this.OnPostop6AyLokalNuksChanging(value);
					this.SendPropertyChanging();
					this._Postop6AyLokalNuks = value;
					this.SendPropertyChanged("Postop6AyLokalNuks");
					this.OnPostop6AyLokalNuksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop6AyKreatin", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> Postop6AyKreatin
		{
			get
			{
				return this._Postop6AyKreatin;
			}
			set
			{
				if ((this._Postop6AyKreatin != value))
				{
					this.OnPostop6AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._Postop6AyKreatin = value;
					this.SendPropertyChanged("Postop6AyKreatin");
					this.OnPostop6AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop12AyLokalNuks", DbType="NVarChar(5)")]
		public string Postop12AyLokalNuks
		{
			get
			{
				return this._Postop12AyLokalNuks;
			}
			set
			{
				if ((this._Postop12AyLokalNuks != value))
				{
					this.OnPostop12AyLokalNuksChanging(value);
					this.SendPropertyChanging();
					this._Postop12AyLokalNuks = value;
					this.SendPropertyChanged("Postop12AyLokalNuks");
					this.OnPostop12AyLokalNuksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop12AyKreatin", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> Postop12AyKreatin
		{
			get
			{
				return this._Postop12AyKreatin;
			}
			set
			{
				if ((this._Postop12AyKreatin != value))
				{
					this.OnPostop12AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._Postop12AyKreatin = value;
					this.SendPropertyChanged("Postop12AyKreatin");
					this.OnPostop12AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblTakipVerileri", Storage="_tblHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblTakipVerileris.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblTakipVerileris.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDemografik")]
	public partial class tblDemografik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private System.Nullable<int> _Yas;
		
		private System.Nullable<decimal> _Boy_cm_;
		
		private System.Nullable<decimal> _Kilo_kg_;
		
		private System.Nullable<int> _BMI;
		
		private System.Nullable<int> _ASA;
		
		private string _DrAdi;
		
		private string _CINS;
		
		private string _Taraf;
		
		private string _Lokalizasyon;
		
		private System.Nullable<int> _Boyut;
		
		private string _KOMorbidite;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnYasChanging(System.Nullable<int> value);
    partial void OnYasChanged();
    partial void OnBoy_cm_Changing(System.Nullable<decimal> value);
    partial void OnBoy_cm_Changed();
    partial void OnKilo_kg_Changing(System.Nullable<decimal> value);
    partial void OnKilo_kg_Changed();
    partial void OnBMIChanging(System.Nullable<int> value);
    partial void OnBMIChanged();
    partial void OnASAChanging(System.Nullable<int> value);
    partial void OnASAChanged();
    partial void OnDrAdiChanging(string value);
    partial void OnDrAdiChanged();
    partial void OnCINSChanging(string value);
    partial void OnCINSChanged();
    partial void OnTarafChanging(string value);
    partial void OnTarafChanged();
    partial void OnLokalizasyonChanging(string value);
    partial void OnLokalizasyonChanged();
    partial void OnBoyutChanging(System.Nullable<int> value);
    partial void OnBoyutChanged();
    partial void OnKOMorbiditeChanging(string value);
    partial void OnKOMorbiditeChanged();
    #endregion
		
		public tblDemografik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yas", DbType="Int")]
		public System.Nullable<int> Yas
		{
			get
			{
				return this._Yas;
			}
			set
			{
				if ((this._Yas != value))
				{
					this.OnYasChanging(value);
					this.SendPropertyChanging();
					this._Yas = value;
					this.SendPropertyChanged("Yas");
					this.OnYasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Boy(cm)]", Storage="_Boy_cm_", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Boy_cm_
		{
			get
			{
				return this._Boy_cm_;
			}
			set
			{
				if ((this._Boy_cm_ != value))
				{
					this.OnBoy_cm_Changing(value);
					this.SendPropertyChanging();
					this._Boy_cm_ = value;
					this.SendPropertyChanged("Boy_cm_");
					this.OnBoy_cm_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Kilo(kg)]", Storage="_Kilo_kg_", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Kilo_kg_
		{
			get
			{
				return this._Kilo_kg_;
			}
			set
			{
				if ((this._Kilo_kg_ != value))
				{
					this.OnKilo_kg_Changing(value);
					this.SendPropertyChanging();
					this._Kilo_kg_ = value;
					this.SendPropertyChanged("Kilo_kg_");
					this.OnKilo_kg_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Int")]
		public System.Nullable<int> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASA", DbType="Int")]
		public System.Nullable<int> ASA
		{
			get
			{
				return this._ASA;
			}
			set
			{
				if ((this._ASA != value))
				{
					this.OnASAChanging(value);
					this.SendPropertyChanging();
					this._ASA = value;
					this.SendPropertyChanged("ASA");
					this.OnASAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrAdi", DbType="NVarChar(255)")]
		public string DrAdi
		{
			get
			{
				return this._DrAdi;
			}
			set
			{
				if ((this._DrAdi != value))
				{
					this.OnDrAdiChanging(value);
					this.SendPropertyChanging();
					this._DrAdi = value;
					this.SendPropertyChanged("DrAdi");
					this.OnDrAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CINS", DbType="NVarChar(255)")]
		public string CINS
		{
			get
			{
				return this._CINS;
			}
			set
			{
				if ((this._CINS != value))
				{
					this.OnCINSChanging(value);
					this.SendPropertyChanging();
					this._CINS = value;
					this.SendPropertyChanged("CINS");
					this.OnCINSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taraf", DbType="NVarChar(255)")]
		public string Taraf
		{
			get
			{
				return this._Taraf;
			}
			set
			{
				if ((this._Taraf != value))
				{
					this.OnTarafChanging(value);
					this.SendPropertyChanging();
					this._Taraf = value;
					this.SendPropertyChanged("Taraf");
					this.OnTarafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokalizasyon", DbType="NVarChar(255)")]
		public string Lokalizasyon
		{
			get
			{
				return this._Lokalizasyon;
			}
			set
			{
				if ((this._Lokalizasyon != value))
				{
					this.OnLokalizasyonChanging(value);
					this.SendPropertyChanging();
					this._Lokalizasyon = value;
					this.SendPropertyChanged("Lokalizasyon");
					this.OnLokalizasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="Int")]
		public System.Nullable<int> Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this.OnBoyutChanging(value);
					this.SendPropertyChanging();
					this._Boyut = value;
					this.SendPropertyChanged("Boyut");
					this.OnBoyutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMorbidite", DbType="NVarChar(255)")]
		public string KOMorbidite
		{
			get
			{
				return this._KOMorbidite;
			}
			set
			{
				if ((this._KOMorbidite != value))
				{
					this.OnKOMorbiditeChanging(value);
					this.SendPropertyChanging();
					this._KOMorbidite = value;
					this.SendPropertyChanged("KOMorbidite");
					this.OnKOMorbiditeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDrListesi")]
	public partial class tblDrListesi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DrAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDrAdiChanging(string value);
    partial void OnDrAdiChanged();
    #endregion
		
		public tblDrListesi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrAdi", DbType="NVarChar(50)")]
		public string DrAdi
		{
			get
			{
				return this._DrAdi;
			}
			set
			{
				if ((this._DrAdi != value))
				{
					this.OnDrAdiChanging(value);
					this.SendPropertyChanging();
					this._DrAdi = value;
					this.SendPropertyChanged("DrAdi");
					this.OnDrAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHastaBilgileri")]
	public partial class tblHastaBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaNO;
		
		private string _HastaAdi;
		
		private string _HastaSoyadi;
		
		private string _ProtokolNo;
		
		private System.Nullable<System.DateTime> _OperasyonTarihi;
		
		private string _OperasyonTuru;
		
		private System.Nullable<int> _TakipSuresi_Ay_;
		
		private System.Nullable<int> _Anah;
		
		private EntitySet<tblTakipVerileri> _tblTakipVerileris;
		
		private EntitySet<tblOperatifOzellikler> _tblOperatifOzelliklers;
		
		private EntitySet<tblPatolojikVeriler> _tblPatolojikVerilers;
		
		private EntitySet<tblPosOperatifOzellikleri> _tblPosOperatifOzellikleris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaNOChanging(System.Nullable<int> value);
    partial void OnHastaNOChanged();
    partial void OnHastaAdiChanging(string value);
    partial void OnHastaAdiChanged();
    partial void OnHastaSoyadiChanging(string value);
    partial void OnHastaSoyadiChanged();
    partial void OnProtokolNoChanging(string value);
    partial void OnProtokolNoChanged();
    partial void OnOperasyonTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOperasyonTarihiChanged();
    partial void OnOperasyonTuruChanging(string value);
    partial void OnOperasyonTuruChanged();
    partial void OnTakipSuresi_Ay_Changing(System.Nullable<int> value);
    partial void OnTakipSuresi_Ay_Changed();
    partial void OnAnahChanging(System.Nullable<int> value);
    partial void OnAnahChanged();
    #endregion
		
		public tblHastaBilgileri()
		{
			this._tblTakipVerileris = new EntitySet<tblTakipVerileri>(new Action<tblTakipVerileri>(this.attach_tblTakipVerileris), new Action<tblTakipVerileri>(this.detach_tblTakipVerileris));
			this._tblOperatifOzelliklers = new EntitySet<tblOperatifOzellikler>(new Action<tblOperatifOzellikler>(this.attach_tblOperatifOzelliklers), new Action<tblOperatifOzellikler>(this.detach_tblOperatifOzelliklers));
			this._tblPatolojikVerilers = new EntitySet<tblPatolojikVeriler>(new Action<tblPatolojikVeriler>(this.attach_tblPatolojikVerilers), new Action<tblPatolojikVeriler>(this.detach_tblPatolojikVerilers));
			this._tblPosOperatifOzellikleris = new EntitySet<tblPosOperatifOzellikleri>(new Action<tblPosOperatifOzellikleri>(this.attach_tblPosOperatifOzellikleris), new Action<tblPosOperatifOzellikleri>(this.detach_tblPosOperatifOzellikleris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaNO", DbType="Int")]
		public System.Nullable<int> HastaNO
		{
			get
			{
				return this._HastaNO;
			}
			set
			{
				if ((this._HastaNO != value))
				{
					this.OnHastaNOChanging(value);
					this.SendPropertyChanging();
					this._HastaNO = value;
					this.SendPropertyChanged("HastaNO");
					this.OnHastaNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaAdi", DbType="NVarChar(50)")]
		public string HastaAdi
		{
			get
			{
				return this._HastaAdi;
			}
			set
			{
				if ((this._HastaAdi != value))
				{
					this.OnHastaAdiChanging(value);
					this.SendPropertyChanging();
					this._HastaAdi = value;
					this.SendPropertyChanged("HastaAdi");
					this.OnHastaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaSoyadi", DbType="NVarChar(50)")]
		public string HastaSoyadi
		{
			get
			{
				return this._HastaSoyadi;
			}
			set
			{
				if ((this._HastaSoyadi != value))
				{
					this.OnHastaSoyadiChanging(value);
					this.SendPropertyChanging();
					this._HastaSoyadi = value;
					this.SendPropertyChanged("HastaSoyadi");
					this.OnHastaSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProtokolNo", DbType="NVarChar(50)")]
		public string ProtokolNo
		{
			get
			{
				return this._ProtokolNo;
			}
			set
			{
				if ((this._ProtokolNo != value))
				{
					this.OnProtokolNoChanging(value);
					this.SendPropertyChanging();
					this._ProtokolNo = value;
					this.SendPropertyChanged("ProtokolNo");
					this.OnProtokolNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperasyonTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> OperasyonTarihi
		{
			get
			{
				return this._OperasyonTarihi;
			}
			set
			{
				if ((this._OperasyonTarihi != value))
				{
					this.OnOperasyonTarihiChanging(value);
					this.SendPropertyChanging();
					this._OperasyonTarihi = value;
					this.SendPropertyChanged("OperasyonTarihi");
					this.OnOperasyonTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperasyonTuru", DbType="NVarChar(100)")]
		public string OperasyonTuru
		{
			get
			{
				return this._OperasyonTuru;
			}
			set
			{
				if ((this._OperasyonTuru != value))
				{
					this.OnOperasyonTuruChanging(value);
					this.SendPropertyChanging();
					this._OperasyonTuru = value;
					this.SendPropertyChanged("OperasyonTuru");
					this.OnOperasyonTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TakipSuresi(Ay)]", Storage="_TakipSuresi_Ay_", DbType="Int")]
		public System.Nullable<int> TakipSuresi_Ay_
		{
			get
			{
				return this._TakipSuresi_Ay_;
			}
			set
			{
				if ((this._TakipSuresi_Ay_ != value))
				{
					this.OnTakipSuresi_Ay_Changing(value);
					this.SendPropertyChanging();
					this._TakipSuresi_Ay_ = value;
					this.SendPropertyChanged("TakipSuresi_Ay_");
					this.OnTakipSuresi_Ay_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anah", DbType="Int")]
		public System.Nullable<int> Anah
		{
			get
			{
				return this._Anah;
			}
			set
			{
				if ((this._Anah != value))
				{
					this.OnAnahChanging(value);
					this.SendPropertyChanging();
					this._Anah = value;
					this.SendPropertyChanged("Anah");
					this.OnAnahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblTakipVerileri", Storage="_tblTakipVerileris", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblTakipVerileri> tblTakipVerileris
		{
			get
			{
				return this._tblTakipVerileris;
			}
			set
			{
				this._tblTakipVerileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblOperatifOzellikler", Storage="_tblOperatifOzelliklers", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblOperatifOzellikler> tblOperatifOzelliklers
		{
			get
			{
				return this._tblOperatifOzelliklers;
			}
			set
			{
				this._tblOperatifOzelliklers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPatolojikVeriler", Storage="_tblPatolojikVerilers", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblPatolojikVeriler> tblPatolojikVerilers
		{
			get
			{
				return this._tblPatolojikVerilers;
			}
			set
			{
				this._tblPatolojikVerilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPosOperatifOzellikleri", Storage="_tblPosOperatifOzellikleris", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblPosOperatifOzellikleri> tblPosOperatifOzellikleris
		{
			get
			{
				return this._tblPosOperatifOzellikleris;
			}
			set
			{
				this._tblPosOperatifOzellikleris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTakipVerileris(tblTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblTakipVerileris(tblTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblOperatifOzelliklers(tblOperatifOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblOperatifOzelliklers(tblOperatifOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblPatolojikVerilers(tblPatolojikVeriler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblPatolojikVerilers(tblPatolojikVeriler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblPosOperatifOzellikleris(tblPosOperatifOzellikleri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblPosOperatifOzellikleris(tblPosOperatifOzellikleri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKOMorbidite")]
	public partial class tblKOMorbidite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KO_Morbidite;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKO_MorbiditeChanging(string value);
    partial void OnKO_MorbiditeChanged();
    #endregion
		
		public tblKOMorbidite()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[KO-Morbidite]", Storage="_KO_Morbidite", DbType="NVarChar(255)")]
		public string KO_Morbidite
		{
			get
			{
				return this._KO_Morbidite;
			}
			set
			{
				if ((this._KO_Morbidite != value))
				{
					this.OnKO_MorbiditeChanging(value);
					this.SendPropertyChanging();
					this._KO_Morbidite = value;
					this.SendPropertyChanged("KO_Morbidite");
					this.OnKO_MorbiditeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOperasyonTuru")]
	public partial class tblOperasyonTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _OperasyonTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOperasyonTuruChanging(string value);
    partial void OnOperasyonTuruChanged();
    #endregion
		
		public tblOperasyonTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperasyonTuru", DbType="NVarChar(255)")]
		public string OperasyonTuru
		{
			get
			{
				return this._OperasyonTuru;
			}
			set
			{
				if ((this._OperasyonTuru != value))
				{
					this.OnOperasyonTuruChanging(value);
					this.SendPropertyChanging();
					this._OperasyonTuru = value;
					this.SendPropertyChanged("OperasyonTuru");
					this.OnOperasyonTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOperatifOzellikler")]
	public partial class tblOperatifOzellikler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PKSAciklama;
		
		private string _SIK;
		
		private string _COOperasyon;
		
		private System.Nullable<int> _Iskemi;
		
		private System.Nullable<int> _PortSayisi;
		
		private string _YardimYNT;
		
		private System.Nullable<int> _Sure;
		
		private System.Nullable<int> _Dren;
		
		private System.Nullable<int> _Kanama;
		
		private System.Nullable<int> _Piyes;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPKSAciklamaChanging(string value);
    partial void OnPKSAciklamaChanged();
    partial void OnSIKChanging(string value);
    partial void OnSIKChanged();
    partial void OnCOOperasyonChanging(string value);
    partial void OnCOOperasyonChanged();
    partial void OnIskemiChanging(System.Nullable<int> value);
    partial void OnIskemiChanged();
    partial void OnPortSayisiChanging(System.Nullable<int> value);
    partial void OnPortSayisiChanged();
    partial void OnYardimYNTChanging(string value);
    partial void OnYardimYNTChanged();
    partial void OnSureChanging(System.Nullable<int> value);
    partial void OnSureChanged();
    partial void OnDrenChanging(System.Nullable<int> value);
    partial void OnDrenChanged();
    partial void OnKanamaChanging(System.Nullable<int> value);
    partial void OnKanamaChanged();
    partial void OnPiyesChanging(System.Nullable<int> value);
    partial void OnPiyesChanged();
    #endregion
		
		public tblOperatifOzellikler()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKSAciklama", DbType="NVarChar(255)")]
		public string PKSAciklama
		{
			get
			{
				return this._PKSAciklama;
			}
			set
			{
				if ((this._PKSAciklama != value))
				{
					this.OnPKSAciklamaChanging(value);
					this.SendPropertyChanging();
					this._PKSAciklama = value;
					this.SendPropertyChanged("PKSAciklama");
					this.OnPKSAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIK", DbType="NVarChar(255)")]
		public string SIK
		{
			get
			{
				return this._SIK;
			}
			set
			{
				if ((this._SIK != value))
				{
					this.OnSIKChanging(value);
					this.SendPropertyChanging();
					this._SIK = value;
					this.SendPropertyChanged("SIK");
					this.OnSIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COOperasyon", DbType="NVarChar(255)")]
		public string COOperasyon
		{
			get
			{
				return this._COOperasyon;
			}
			set
			{
				if ((this._COOperasyon != value))
				{
					this.OnCOOperasyonChanging(value);
					this.SendPropertyChanging();
					this._COOperasyon = value;
					this.SendPropertyChanged("COOperasyon");
					this.OnCOOperasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iskemi", DbType="Int")]
		public System.Nullable<int> Iskemi
		{
			get
			{
				return this._Iskemi;
			}
			set
			{
				if ((this._Iskemi != value))
				{
					this.OnIskemiChanging(value);
					this.SendPropertyChanging();
					this._Iskemi = value;
					this.SendPropertyChanged("Iskemi");
					this.OnIskemiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortSayisi", DbType="Int")]
		public System.Nullable<int> PortSayisi
		{
			get
			{
				return this._PortSayisi;
			}
			set
			{
				if ((this._PortSayisi != value))
				{
					this.OnPortSayisiChanging(value);
					this.SendPropertyChanging();
					this._PortSayisi = value;
					this.SendPropertyChanged("PortSayisi");
					this.OnPortSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YardimYNT", DbType="NVarChar(255)")]
		public string YardimYNT
		{
			get
			{
				return this._YardimYNT;
			}
			set
			{
				if ((this._YardimYNT != value))
				{
					this.OnYardimYNTChanging(value);
					this.SendPropertyChanging();
					this._YardimYNT = value;
					this.SendPropertyChanged("YardimYNT");
					this.OnYardimYNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int")]
		public System.Nullable<int> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="Int")]
		public System.Nullable<int> Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kanama", DbType="Int")]
		public System.Nullable<int> Kanama
		{
			get
			{
				return this._Kanama;
			}
			set
			{
				if ((this._Kanama != value))
				{
					this.OnKanamaChanging(value);
					this.SendPropertyChanging();
					this._Kanama = value;
					this.SendPropertyChanged("Kanama");
					this.OnKanamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piyes", DbType="Int")]
		public System.Nullable<int> Piyes
		{
			get
			{
				return this._Piyes;
			}
			set
			{
				if ((this._Piyes != value))
				{
					this.OnPiyesChanging(value);
					this.SendPropertyChanging();
					this._Piyes = value;
					this.SendPropertyChanged("Piyes");
					this.OnPiyesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblOperatifOzellikler", Storage="_tblHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblOperatifOzelliklers.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblOperatifOzelliklers.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPatoloji")]
	public partial class tblPatoloji : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Patoloji;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPatolojiChanging(string value);
    partial void OnPatolojiChanged();
    #endregion
		
		public tblPatoloji()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NVarChar(255)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this.OnPatolojiChanging(value);
					this.SendPropertyChanging();
					this._Patoloji = value;
					this.SendPropertyChanged("Patoloji");
					this.OnPatolojiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPatolojikVeriler")]
	public partial class tblPatolojikVeriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _Patoloji;
		
		private string _AltGrup;
		
		private string _FurhmanGrade;
		
		private string _PatolojikEvre;
		
		private string _CerrahiSinir;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPatolojiChanging(string value);
    partial void OnPatolojiChanged();
    partial void OnAltGrupChanging(string value);
    partial void OnAltGrupChanged();
    partial void OnFurhmanGradeChanging(string value);
    partial void OnFurhmanGradeChanged();
    partial void OnPatolojikEvreChanging(string value);
    partial void OnPatolojikEvreChanged();
    partial void OnCerrahiSinirChanging(string value);
    partial void OnCerrahiSinirChanged();
    #endregion
		
		public tblPatolojikVeriler()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NVarChar(50)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this.OnPatolojiChanging(value);
					this.SendPropertyChanging();
					this._Patoloji = value;
					this.SendPropertyChanged("Patoloji");
					this.OnPatolojiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGrup", DbType="NVarChar(150)")]
		public string AltGrup
		{
			get
			{
				return this._AltGrup;
			}
			set
			{
				if ((this._AltGrup != value))
				{
					this.OnAltGrupChanging(value);
					this.SendPropertyChanging();
					this._AltGrup = value;
					this.SendPropertyChanged("AltGrup");
					this.OnAltGrupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FurhmanGrade", DbType="NVarChar(50)")]
		public string FurhmanGrade
		{
			get
			{
				return this._FurhmanGrade;
			}
			set
			{
				if ((this._FurhmanGrade != value))
				{
					this.OnFurhmanGradeChanging(value);
					this.SendPropertyChanging();
					this._FurhmanGrade = value;
					this.SendPropertyChanged("FurhmanGrade");
					this.OnFurhmanGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatolojikEvre", DbType="NVarChar(20)")]
		public string PatolojikEvre
		{
			get
			{
				return this._PatolojikEvre;
			}
			set
			{
				if ((this._PatolojikEvre != value))
				{
					this.OnPatolojikEvreChanging(value);
					this.SendPropertyChanging();
					this._PatolojikEvre = value;
					this.SendPropertyChanged("PatolojikEvre");
					this.OnPatolojikEvreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CerrahiSinir", DbType="NVarChar(10)")]
		public string CerrahiSinir
		{
			get
			{
				return this._CerrahiSinir;
			}
			set
			{
				if ((this._CerrahiSinir != value))
				{
					this.OnCerrahiSinirChanging(value);
					this.SendPropertyChanging();
					this._CerrahiSinir = value;
					this.SendPropertyChanged("CerrahiSinir");
					this.OnCerrahiSinirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPatolojikVeriler", Storage="_tblHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblPatolojikVerilers.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblPatolojikVerilers.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPosOperatifOzellikleri")]
	public partial class tblPosOperatifOzellikleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _Perop_ErkenKomp;
		
		private string _Dren;
		
		private string _PostopAnaliz;
		
		private string _Sonda;
		
		private System.Nullable<int> _HospSuresi;
		
		private System.Nullable<decimal> _PreopKreatin;
		
		private System.Nullable<decimal> _PostopKreatin;
		
		private System.Nullable<decimal> _PreopHCT;
		
		private System.Nullable<decimal> _PostopHCT;
		
		private System.Nullable<decimal> _PreopHB;
		
		private System.Nullable<decimal> _PostopHB;
		
		private string _Takip;
		
		private string _Tel;
		
		private string _PostopGecKomp;
		
		private string _KompClavien;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPerop_ErkenKompChanging(string value);
    partial void OnPerop_ErkenKompChanged();
    partial void OnDrenChanging(string value);
    partial void OnDrenChanged();
    partial void OnPostopAnalizChanging(string value);
    partial void OnPostopAnalizChanged();
    partial void OnSondaChanging(string value);
    partial void OnSondaChanged();
    partial void OnHospSuresiChanging(System.Nullable<int> value);
    partial void OnHospSuresiChanged();
    partial void OnPreopKreatinChanging(System.Nullable<decimal> value);
    partial void OnPreopKreatinChanged();
    partial void OnPostopKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostopKreatinChanged();
    partial void OnPreopHCTChanging(System.Nullable<decimal> value);
    partial void OnPreopHCTChanged();
    partial void OnPostopHCTChanging(System.Nullable<decimal> value);
    partial void OnPostopHCTChanged();
    partial void OnPreopHBChanging(System.Nullable<decimal> value);
    partial void OnPreopHBChanged();
    partial void OnPostopHBChanging(System.Nullable<decimal> value);
    partial void OnPostopHBChanged();
    partial void OnTakipChanging(string value);
    partial void OnTakipChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnPostopGecKompChanging(string value);
    partial void OnPostopGecKompChanged();
    partial void OnKompClavienChanging(string value);
    partial void OnKompClavienChanged();
    #endregion
		
		public tblPosOperatifOzellikleri()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Perop-ErkenKomp]", Storage="_Perop_ErkenKomp", DbType="NVarChar(255)")]
		public string Perop_ErkenKomp
		{
			get
			{
				return this._Perop_ErkenKomp;
			}
			set
			{
				if ((this._Perop_ErkenKomp != value))
				{
					this.OnPerop_ErkenKompChanging(value);
					this.SendPropertyChanging();
					this._Perop_ErkenKomp = value;
					this.SendPropertyChanged("Perop_ErkenKomp");
					this.OnPerop_ErkenKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="NVarChar(255)")]
		public string Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopAnaliz", DbType="NVarChar(255)")]
		public string PostopAnaliz
		{
			get
			{
				return this._PostopAnaliz;
			}
			set
			{
				if ((this._PostopAnaliz != value))
				{
					this.OnPostopAnalizChanging(value);
					this.SendPropertyChanging();
					this._PostopAnaliz = value;
					this.SendPropertyChanged("PostopAnaliz");
					this.OnPostopAnalizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonda", DbType="NVarChar(255)")]
		public string Sonda
		{
			get
			{
				return this._Sonda;
			}
			set
			{
				if ((this._Sonda != value))
				{
					this.OnSondaChanging(value);
					this.SendPropertyChanging();
					this._Sonda = value;
					this.SendPropertyChanged("Sonda");
					this.OnSondaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospSuresi", DbType="Int")]
		public System.Nullable<int> HospSuresi
		{
			get
			{
				return this._HospSuresi;
			}
			set
			{
				if ((this._HospSuresi != value))
				{
					this.OnHospSuresiChanging(value);
					this.SendPropertyChanging();
					this._HospSuresi = value;
					this.SendPropertyChanged("HospSuresi");
					this.OnHospSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PreopKreatin
		{
			get
			{
				return this._PreopKreatin;
			}
			set
			{
				if ((this._PreopKreatin != value))
				{
					this.OnPreopKreatinChanging(value);
					this.SendPropertyChanging();
					this._PreopKreatin = value;
					this.SendPropertyChanged("PreopKreatin");
					this.OnPreopKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostopKreatin
		{
			get
			{
				return this._PostopKreatin;
			}
			set
			{
				if ((this._PostopKreatin != value))
				{
					this.OnPostopKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostopKreatin = value;
					this.SendPropertyChanged("PostopKreatin");
					this.OnPostopKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopHCT", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PreopHCT
		{
			get
			{
				return this._PreopHCT;
			}
			set
			{
				if ((this._PreopHCT != value))
				{
					this.OnPreopHCTChanging(value);
					this.SendPropertyChanging();
					this._PreopHCT = value;
					this.SendPropertyChanged("PreopHCT");
					this.OnPreopHCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHCT", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostopHCT
		{
			get
			{
				return this._PostopHCT;
			}
			set
			{
				if ((this._PostopHCT != value))
				{
					this.OnPostopHCTChanging(value);
					this.SendPropertyChanging();
					this._PostopHCT = value;
					this.SendPropertyChanged("PostopHCT");
					this.OnPostopHCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopHB", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PreopHB
		{
			get
			{
				return this._PreopHB;
			}
			set
			{
				if ((this._PreopHB != value))
				{
					this.OnPreopHBChanging(value);
					this.SendPropertyChanging();
					this._PreopHB = value;
					this.SendPropertyChanged("PreopHB");
					this.OnPreopHBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHB", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostopHB
		{
			get
			{
				return this._PostopHB;
			}
			set
			{
				if ((this._PostopHB != value))
				{
					this.OnPostopHBChanging(value);
					this.SendPropertyChanging();
					this._PostopHB = value;
					this.SendPropertyChanged("PostopHB");
					this.OnPostopHBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="NVarChar(255)")]
		public string Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(255)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopGecKomp", DbType="NVarChar(255)")]
		public string PostopGecKomp
		{
			get
			{
				return this._PostopGecKomp;
			}
			set
			{
				if ((this._PostopGecKomp != value))
				{
					this.OnPostopGecKompChanging(value);
					this.SendPropertyChanging();
					this._PostopGecKomp = value;
					this.SendPropertyChanged("PostopGecKomp");
					this.OnPostopGecKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KompClavien", DbType="NVarChar(255)")]
		public string KompClavien
		{
			get
			{
				return this._KompClavien;
			}
			set
			{
				if ((this._KompClavien != value))
				{
					this.OnKompClavienChanging(value);
					this.SendPropertyChanging();
					this._KompClavien = value;
					this.SendPropertyChanged("KompClavien");
					this.OnKompClavienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPosOperatifOzellikleri", Storage="_tblHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblPosOperatifOzellikleris.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblPosOperatifOzellikleris.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
